### ISSUE TITLE
Wrong Datatype?

### ISSUE THREAD

**Issue by Zric99** [Jonathankli/mariogo#1]
Column "name" has data_type "bigint(20) unsigned". No other reference found quickly. Shouldn't this be a string?

![image](https://github.com/Jonathankli/mariogo/assets/65248246/a13d09ba-52e5-4686-a84a-be3e59024ed9)
![image](https://github.com/Jonathankli/mariogo/assets/65248246/f301b701-77ab-4217-85d5-64965a747236)

**Comment by Jonathankli** [comment]
Yes should be a string!
